name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Vue 3 + TypeScript App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
        working-directory: bondmate-frontend

      - name: Lint Code
        run: pnpm run lint
        working-directory: bondmate-frontend

      - name: Run TypeScript Type Check
        run: pnpm run type-check
        working-directory: bondmate-frontend

      - name: Run Tests
        run: pnpm run test
        working-directory: bondmate-frontend

      - name: Build Project
        run: pnpm run build
        working-directory: bondmate-frontend

  deploy:
    name: Deploy to Azure Static Web Apps
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "bondmate-frontend/dist"
          output_location: "dist"
